stages:
  - build
  - deploy


push:
  stage: deploy
  image: alpine
  variables:
    USER: "gedeop"
    HOST: "147.100.175.144"
    DIR: "./"
 
  before_script:
     - apk add --no-cache openssh-client rsync
     - mkdir -p ~/.ssh
     - touch ~/.ssh/id_rsa
     - echo "$SSH_GEDEOP_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
     - eval $(ssh-agent -s)
     - ssh-add
  script:
     - rsync -ravz --exclude .git --exclude .gitlab-ci.yml $DIR $USER@$HOST:/srv/shiny-server/shiny/cste/

